# Generated by Django 4.0.6 on 2025-09-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
