# Generated by Django 4.0.6 on 2025-09-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
