# Generated by Django 4.0.6 on 2025-09-24 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Группа, к которой будет относиться инструмент', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='instruments.group', verbose_name='Группа'),
        ),
    ]
