# Generated by Django 4.0.6 on 2025-09-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
