# Generated by Django 4.0.6 on 2025-09-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_remove_instrument_group_delete_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(upload_to='instruments/', verbose_name='Изображение инструмента'),
        ),
    ]
